# Generated by Django 5.2.9 on 2026-03-27 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.CharField(choices=[('Present', 'present'), ('Absent', 'absent'), ('Leave', 'leave')], max_length=10),
        ),
    ]
