# Generated by Django 6.0 on 2026-04-04 18:45

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_dailyusage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyusage',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='dailyusage',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usages', to='accounts.inventory'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='worker_id',
            field=models.CharField(blank=True, editable=False, max_length=20, unique=True),
        ),
    ]
