# Generated by Django 6.0 on 2026-04-04 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_dailyusage_date_alter_dailyusage_item_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='worker_id',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
