# Generated by Django 6.0 on 2026-04-07 16:08

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_leaverequest_attachment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='phone_number',
            field=models.CharField(blank=True, max_length=10, null=True, validators=[django.core.validators.RegexValidator(message='Phone number must be 10 digits and cannot start with 0.', regex='^[1-9]\\d{9}$')]),
        ),
        migrations.AlterField(
            model_name='worker',
            name='university_record',
            field=models.OneToOneField(blank=True, limit_choices_to={'role': 'worker'}, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.universityid'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='worker_id',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
    ]
