# Generated by Django 6.0 on 2026-04-29 05:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_leaverequest_worker_master'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='worker',
            name='is_approved',
        ),
    ]
